name: Release Power Platform Solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The name of the Power Platform solution'
        required: true
      solution_target_folder:
        description: 'The target folder for the managed solution'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Power Platform CLI
        run: npm install -g pac

      - name: Authenticate with Power Platform
        run: pac auth create --url https://dev-aliii.crm.dynamics.com/ --name "OrgName" --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Export Solution as Managed
        run: |
          pac solution export --path "${{ github.event.inputs.solution_target_folder }}/managed.zip" --name "${{ github.event.inputs.solution_name }}" --managed --async --max-async-wait-time 60

      - name: Upload Managed Solution
        uses: actions/upload-artifact@v3
        with:
          name: managed-solution
          path: "${{ github.event.inputs.solution_target_folder }}/managed.zip"

      - name: Trigger Test Environment Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const dispatch = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-to-test.yml',
              ref: context.ref,
              inputs: {
                solution_name: "${{ github.event.inputs.solution_name }}",
                solution_target_folder: "${{ github.event.inputs.solution_target_folder }}"
              }
            });
