name: Deploy to Production

on:
  workflow_run:
    workflows: ["Deploy to Test"]
    types:
      - completed

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        run: echo "Waiting for approval to deploy to Production."
        # Send a notification or pause for approval

  deploy:
    runs-on: ubuntu-latest
    needs: approve
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
      url: https://your-production-env-url

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: solution-artifacts

      - name: Authenticate with Power Platform
        run: pac auth create --url https://your-prod-env.crm.dynamics.com --name "ProdEnv" --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --tenant-id ${{ secrets.TENANT_ID }}

      - name: Import Solution to Production Environment
        run: pac solution import --path "path/to/solution.zip" --async --max-async-wait-time 60
