name: Deploy to Test

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to Test Environment
        run: |
          # Replace with your deployment script
          echo "Deploying to Test environment"
