name: Deploy to Test

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: solution-artifacts

      - name: Authenticate with Power Platform
        run: pac auth create --url https://your-test-env.crm.dynamics.com --name "TestEnv" --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --tenant-id ${{ secrets.TENANT_ID }}

      - name: Import Solution to Test Environment
        run: pac solution import --path "path/to/solution.zip" --async --max-async-wait-time 60
