name: Deploy to Test Environment

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The name of the Power Platform solution'
        required: true
      solution_target_folder:
        description: 'The target folder for the managed solution'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Managed Solution
        uses: actions/download-artifact@v3
        with:
          name: managed-solution

      - name: Authenticate with Power Platform
        run: pac auth create --url https://dvm-aliii.crm.dynamics.com/ --name "TEST_POWER_PLATFORM_URL" --client-id ${{ secrets.AZURE_CLIENT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Import Solution to Test Environment
        run: pac solution import --path "${{ github.event.inputs.solution_target_folder }}/managed.zip" --async --max-async-wait-time 60

      - name: Trigger Production Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const dispatch = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-to-prod.yml',
              ref: context.ref,
              inputs: {
                solution_name: "${{ github.event.inputs.solution_name }}",
                solution_target_folder: "${{ github.event.inputs.solution_target_folder }}"
              }
            });
