name: Deploy to Production

on:
  workflow_run:
    workflows: ["Deploy to Test"]
    types:
      - completed

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        run: echo "Waiting for approval to deploy to Production."
        # Send a notification or pause for approval

  deploy:
    runs-on: ubuntu-latest
    needs: approve
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
      url: https://your-production-env-url

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to Production
        run: |
          # Replace with your deployment script
          echo "Deploying to Production environment"
